import { avenir, fragmentGlare, fragmentSans } from "./typefaces";
import "./globals.css";
import LenisSmoothScroll from "@/components/Lenis/SmoothScroll";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Don't Forget Us",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${avenir.variable} ${fragmentSans.variable} ${fragmentGlare.variable} antialiased`}
    >
      <body className="min-h-dvh flex flex-col font-sans">
        <LenisSmoothScroll>
          <Navbar />
          {children}
        </LenisSmoothScroll>
      </body>
    </html>
  );
}
